# To test with http://editor.swagger.io/
openapi: 3.0.0
info:
  title: Food for thought API
  version: 1.0.0
servers:
- url: http://localhost:5000/api
  description: Local server
components:
  responses:
    NotFound:
      description: Resource not found
    BadRequest:
      description: Bad request
    UnauthorizedAccess:
      description: User cannot access this resource
  schemas:
    MediaMessage:
      description: Media message
      type: object
      properties:
        id:
          type: string
          description: The Message ID.
        author:
          type: string
          description: Message author.
        text:
          type: string
          description: Message text content.
        createdAt:
          type: string
          description: Message creation date.
        media:
          type: object
          properties:
            source:
              type: object
              properties:
                name:
                  type: string
                  description: Source name.
                icon:
                  type: string
                  description: Source icon.
                link:
                  type: string
                  description: Source link.
            title:
              type: string
              description: Media title.
            headline:
              type: string
              description: Article headline.
            image:
              type: string
              description: Media image.
            thumb:
              type: string
              description: Media thumb image.
    Channel:
      description: Media message
      type: object
      properties:
        channelId:
          type: string
          description: The Message ID.
        author:
          type: string
          description: Message author.
        text:
          type: string
          description: Message text content.
        createdAt:
          type: string
          description: Message creation date.
        media:
          type: object
          properties:
            source:
              type: object
              properties:
                name:
                  type: string
                  description: Source name.
                icon:
                  type: string
                  description: Source icon.
                link:
                  type: string
                  description: Source link.
            title:
              type: string
              description: Media title.
            text:
              type: string
              description: Media text.
            image:
              type: string
              description: Media image.
            thumb:
              type: string
              description: Media thumb image.
paths:
  /medias:
    get:
      summary: Get medias messages
      tags:
      - Messages
      responses:
        '200':
          description: Media messages returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/MediaMessage'
  /channels:
    get:
      summary: Get channels
      tags:
      - Channels
      responses:
        '200':
          description: Channels returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  channels:
                    type: array
                    items:
                      $ref: '#/components/schemas/MediaMessage'